name: 'Test PHP Version'

on:
  pull_request:
    branches:
    - main

jobs:
  php74:
    runs-on: ubuntu-latest
    name: Expect 7.4
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Start wp-env
        uses: ./
        with:
          phpVersion: "7.4"

      - name: Expect PHP version 7.4
        run: |
          wp-env run cli "php -v"
          if [[ $(wp-env run cli "php -v") != "PHP 7.4"* ]]; then exit 1; fi
